apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicacount   }}
  selector:
    matchLabels:
      {{- include "dep.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dep.labels" . | nindent 8 }}
    spec:
      containers:
      - name: con1
        image: {{ .Values.con1.image }}
        ports:
        - containerPort: {{ .Values.con1.port }}

