apiVersion: v1
kind: LimitRange
metadata:
   name: devops-lr
   namespace: devops
spec:
  limits:
  - default:
       cpu: 1000m
       memory: 1Gi
    defaultRequest: 
      cpu: 100m
      memory: 128Mi
    type: Container
