apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ing
spec:
  tls:
  - hosts:
      - aneesh.com
    secretName: aneesh-com
  ingressClassName: nginx
  rules:
  - host: "aneesh.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mydep-svc
            port:
              number: 80
