apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: green
spec:
  volumes:
  - name: myvol
    secret:
      secretName: appcrt
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: myvol
      mountPath: "/app"
      readOnly: true
