apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-net
  namespace: default
spec:
  podSelector:
    matchLabels:
       app: mydb
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: wordpress
    ports:
    - protocol: TCP
      port: 3306


