apiVersion: v1
kind: Pod
metadata:
  name: wordpress2
  labels:
    app: wordpress2
spec:
  containers:
  - name: con1
    image: wordpress:latest
    ports:
    - containerPort: 80
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql-svc
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: test123
    - name: WORDPRESS_DB_NAME
      value: wpdb
    - name: WORDPRESS_TABLE_PREFIX
      value: wp2_


---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc2
spec:
  type: NodePort
  selector:
    app: wordpress2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30125

